{{- if and (eq (index .Values.configProperties "storage.type") "postgresql") .Values.flyway.enabled }}
---
apiVersion: v1
metadata:
  labels:
    app.kubernetes.io/name: {{ include "owanalytics.name" . }}
    helm.sh/chart: {{ include "owanalytics.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "owanalytics.fullname" . }}-flyway
kind: Secret
type: Opaque
data:
  FLYWAY_USER: {{ index .Values.configProperties "storage.type.postgresql.username" | b64enc | quote }}
  FLYWAY_PASSWORD: {{ index .Values.configProperties "storage.type.postgresql.password" | b64enc | quote }}
{{- end }}
